In [1]:

!pip install requests beautifulsoup4 pandas

Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (2.32.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.13/dist-packages (4.13.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests) (2026.7.22)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4) (4.16.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import time
import requests
import pandas as pd
from bs4 import BeautifulSoup

In [8]:
url = "https://theamazingworldofgumball.fandom.com/wiki/The_Amazing_World_of_Gumball_Wiki"

headers = {
    "User-Agent": "Mozilla/5.0"
}

In [9]:
response = requests.get(
    url,
    headers=headers,
    timeout=20
)

print("Status Code:", response.status_code)

Status Code: 403

In [10]:
import requests
from bs4 import BeautifulSoup

api_url = "https://theamazingworldofgumball.fandom.com/api.php"

params = {
    "action": "parse",
    "page": "The Amazing World of Gumball Wiki",
    "prop": "text",
    "format": "json",
    "formatversion": "2"
}

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(
    api_url,
    params=params,
    headers=headers
)

print(response.status_code)

200

In [16]:
data = response.json()

html = data["parse"]["text"]

soup = BeautifulSoup(
    html,
    "html.parser"
)

print("Berhasil mendapatkan halaman!")

Berhasil mendapatkan halaman!

In [17]:
judul = data["parse"]["title"]

print("Judul halaman:", judul)

Judul halaman: The Amazing World of Gumball Wiki

In [18]:
data["parse"]["title"]

'The Amazing World of Gumball Wiki'

In [19]:
print(soup.get_text(" ", strip=True)[:1000])

Welcome! Welcome to the Amazing World of Gumball Wiki, the Gumball encyclopedia! The Wattersons Meet the not-so-average family, the Wattersons! Read more > New Gumball episodes are coming soon! More episodes of The Wonderfully Weird World of Gumball are out in the US and internationally! Read more > Featured Song We thought that we would always be by each other's side... Read more > Latest Episode Gumball and Darwin are close to finding out the truth about Elmore, but Rob has other plans... Read more > 〈 〉 Welcome to 2,200 articles and growing... Need help? Rules Fanon Character guide Episode guide Locations Community Brain Freeze by Gameuser10 Congratulations to Gameuser10 for winning third place in the Wiki's Summer 2020 Art Contest! See all the other great submissions here ! Neophyte (by Gameuser10) "With man's technological evolution, more are pushed to question the relationship between mankind and technology, and ponder where exactly humanity stands within modern society's moral a

In [20]:
paragraphs = soup.find_all("p")

print("Jumlah paragraf:", len(paragraphs))

Jumlah paragraf: 59

In [21]:
for p in paragraphs[:10]:
    text = p.get_text(" ", strip=True)

    if text:
        print(text)
        print()

Welcome to the Amazing World of Gumball Wiki, the Gumball encyclopedia!

Meet the not-so-average family, the Wattersons!

Read more >

More episodes of The Wonderfully Weird World of Gumball are out in the US and internationally!

Read more >

We thought that we would always be by each other's side...

Read more >

Gumball and Darwin are close to finding out the truth about Elmore, but Rob has other plans...

Read more >

In [22]:
paragraph_list = []

for p in soup.find_all("p"):
    text = p.get_text(" ", strip=True)

    if text:
        paragraph_list.append(text)

In [24]:
paragraph_list[:10]

['Welcome to the Amazing World of Gumball Wiki, the Gumball encyclopedia!',
 'Meet the not-so-average family, the Wattersons!',
 'Read more >',
 'More episodes of The Wonderfully Weird World of Gumball are out in the US and internationally!',
 'Read more >',
 "We thought that we would always be by each other's side...",
 'Read more >',
 'Gumball and Darwin are close to finding out the truth about Elmore, but Rob has other plans...',
 'Read more >',
 '〈 〉']

In [23]:
headings = []

for heading in soup.select("h2, h3"):
    text = heading.get_text(" ", strip=True)

    if text:
        headings.append(text)

In [25]:
for heading in headings:
    print(heading)

Welcome!
The Wattersons
New Gumball episodes are coming soon!
Featured Song
Latest Episode
Blogs
The Cancellationgation Predictions
Sorry What?!
Nevermind

In [26]:
from urllib.parse import urljoin

In [27]:
base_url = "https://theamazingworldofgumball.fandom.com"

links = []

for a in soup.find_all("a", href=True):

    text = a.get_text(" ", strip=True)
    href = a["href"]

    if href.startswith("/wiki/") and text:

        full_url = urljoin(base_url, href)

        links.append({
            "Nama": text,
            "URL": full_url
        })

In [29]:
df = pd.DataFrame(links)

df.head(20)

,Nama,URL
0,Read more >,https://theamazingworldofgumball.fandom.com/wi...
1,Read more >,https://theamazingworldofgumball.fandom.com/wi...
2,Read more >,https://theamazingworldofgumball.fandom.com/wi...
3,Read more >,https://theamazingworldofgumball.fandom.com/wi...
4,"2,200",https://theamazingworldofgumball.fandom.com/wi...
5,Need help?,https://theamazingworldofgumball.fandom.com/wi...
6,Rules,https://theamazingworldofgumball.fandom.com/wi...
7,Character guide,https://theamazingworldofgumball.fandom.com/wi...
8,Episode guide,https://theamazingworldofgumball.fandom.com/wi...
9,Locations,https://theamazingworldofgumball.fandom.com/wi...
10,Community,https://theamazingworldofgumball.fandom.com/wi...
11,Gameuser10,https://theamazingworldofgumball.fandom.com/wi...
12,Consider entering our contest,https://theamazingworldofgumball.fandom.com/wi...
13,The Wonderfully Weird World of Gumball,https://theamazingworldofgumball.fandom.com/wi...
14,Kaiju,https://theamazingworldofgumball.fandom.com/wi...
15,The Wonderfully Weird World of Gumball,https://theamazingworldofgumball.fandom.com/wi...
16,Mario,https://theamazingworldofgumball.fandom.com/wi...
17,The Wonderfully Weird World of Gumball,https://theamazingworldofgumball.fandom.com/wi...
18,Mario,https://theamazingworldofgumball.fandom.com/wi...
19,The Wonderfully Weird World of Gumball,https://theamazingworldofgumball.fandom.com/wi...

In [30]:
df = df.drop_duplicates()

df = df.reset_index(drop=True)

df

,Nama,URL
0,Read more >,https://theamazingworldofgumball.fandom.com/wi...
1,Read more >,https://theamazingworldofgumball.fandom.com/wi...
2,Read more >,https://theamazingworldofgumball.fandom.com/wi...
3,Read more >,https://theamazingworldofgumball.fandom.com/wi...
4,"2,200",https://theamazingworldofgumball.fandom.com/wi...
5,Need help?,https://theamazingworldofgumball.fandom.com/wi...
6,Rules,https://theamazingworldofgumball.fandom.com/wi...
7,Character guide,https://theamazingworldofgumball.fandom.com/wi...
8,Episode guide,https://theamazingworldofgumball.fandom.com/wi...
9,Locations,https://theamazingworldofgumball.fandom.com/wi...
10,Community,https://theamazingworldofgumball.fandom.com/wi...
11,Gameuser10,https://theamazingworldofgumball.fandom.com/wi...
12,Consider entering our contest,https://theamazingworldofgumball.fandom.com/wi...
13,The Wonderfully Weird World of Gumball,https://theamazingworldofgumball.fandom.com/wi...
14,Kaiju,https://theamazingworldofgumball.fandom.com/wi...
15,Mario,https://theamazingworldofgumball.fandom.com/wi...
16,TheEarthisround12,https://theamazingworldofgumball.fandom.com/wi...
17,Previous winners,https://theamazingworldofgumball.fandom.com/wi...
18,(All affiliations),https://theamazingworldofgumball.fandom.com/wi...
19,The News,https://theamazingworldofgumball.fandom.com/wi...
20,Kip Schlezinger,https://theamazingworldofgumball.fandom.com/wi...
21,Ben Bocquelet,https://theamazingworldofgumball.fandom.com/wi...
22,Richard Overall,https://theamazingworldofgumball.fandom.com/wi...
23,more images,https://theamazingworldofgumball.fandom.com/wi...
24,Character666,https://theamazingworldofgumball.fandom.com/wi...
25,The Cancellationgation Predictions,https://theamazingworldofgumball.fandom.com/wi...
26,Read Full Post,https://theamazingworldofgumball.fandom.com/wi...
27,Sorry What?!,https://theamazingworldofgumball.fandom.com/wi...
28,Read Full Post,https://theamazingworldofgumball.fandom.com/wi...
29,PlankMan123,https://theamazingworldofgumball.fandom.com/wi...
30,Nevermind,https://theamazingworldofgumball.fandom.com/wi...
31,Read Full Post,https://theamazingworldofgumball.fandom.com/wi...

In [31]:
print("Jumlah link:", len(df))

Jumlah link: 32

In [33]:
df.to_csv(
    "gumball_wiki.csv",
    index=False
)